
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.3.0")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                       % "0.2.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"                   % "1.0.13")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "3.8.1")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                    % "5.4.0")
addSbtPlugin("io.spray"           % "sbt-boilerplate"               % "0.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.31")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                       % "0.3.7")
